/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    InputArea: typeof import('./src/components/InputArea.vue')['default']
    MathDisplay: typeof import('./src/components/MathDisplay.vue')['default']
    RndBtn: typeof import('./src/components/RndBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
